name: Deploy ParkHere

# on: [workflow_dispatch]
on:
  push:
    branches:
    - main

jobs:
  web-dev-sync:
    name: üéâ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploying ‚ù§‚ù§
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /www/wwwroot/parkhere.ourproject.my.id
            echo "${{ secrets.PASSWORD }}" | sudo -S git stash
            echo "${{ secrets.PASSWORD }}" | sudo -S git pull origin main
            echo "${{ secrets.PASSWORD }}" | sudo -S composer install
            php artisan route:list
