name: Deploy ParkHere

on: [workflow_dispatch]
# on:
#   push:
#     branches:
#     - master

jobs:
  web-dev-sync:
    name: üéâ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploying ‚ù§‚ù§
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /www/wwwroot/parkhere.ourproject.my.id
            git stash
            echo "${{ secrets.PASSWORD }}" | sudo -S git pull origin main
            echo "${{ secrets.PASSWORD }}" | sudo -S composer install --ignore-platform-req=ext-fileinfo
            echo "${{ secrets.PASSWORD }}" | sudo -S php artisan db:renew --force
            echo "${{ secrets.PASSWORD }}" | sudo -S php artisan db:import
            echo "${{ secrets.PASSWORD }}" | sudo -S php artisan optimize
            echo "${{ secrets.PASSWORD }}" | sudo -S php artisan config:cache
            echo "${{ secrets.PASSWORD }}" | sudo -S php artisan route:cache
            echo "${{ secrets.PASSWORD }}" | sudo -S php artisan view:cache
