name: Deploy ParkHere

# on: [workflow_dispatch]
on:
  push:
    branches:
    - main

jobs:
  web-dev-sync:
    name: üéâ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploying ‚ù§‚ù§
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /www/wwwroot/parkhere.ourproject.my.id
            echo "${{ secrets.PASSWORD }}" | sudo -S echo && sudo -s
            sudo git stash
            sudo git pull
            sudo git pull origin main
            sudo composer install --ignore-platform-reqs
            sudo php artisan db:renew --force
            sudo php artisan db:import
            sudo php artisan optimize
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan view:cache
