name: Deploy ParkHere

on: [workflow_dispatch]
# on:
#   push:
#     branches:
#     - master

jobs:
  web-dev-sync:
    name: üéâ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploying ‚ù§‚ù§
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /www/wwwroot/parkhere.ourproject.my.id
            git stash
            git pull origin main
            sudo --ignore-platform-req=ext-fileinfo
            ${{ secrets.PASSWORD }}
            sudo php artisan db:renew --force
            ${{ secrets.PASSWORD }}
            sudo php artisan db:import
            ${{ secrets.PASSWORD }}
            sudo php artisan optimize
            ${{ secrets.PASSWORD }}
            sudo php artisan config:cache
            ${{ secrets.PASSWORD }}
            sudo php artisan route:cache
            ${{ secrets.PASSWORD }}
            sudo php artisan¬†view:cache
            ${{ secrets.PASSWORD }}
