name: Deploy ParkHere

# on: [workflow_dispatch]
on:
  push:
    branches:
    - main

jobs:
  web-dev-sync:
    name: üéâ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploying ‚ù§‚ù§
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /www/wwwroot/parkhere.ourproject.my.id
            git stash
            git pull
            echo "${{ secrets.PASSWORD }}" | sudo -S echo && sudo -s
            git pull origin main
            composer install --ignore-platform-reqs
            php artisan db:renew --force
            php artisan db:import
            php artisan optimize
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
